# Netlify Configuration for Japanese Learning Tracker

[build]
  # No build command needed for static HTML site
  publish = "."
  
[build.environment]
  # Environment variables are set in Netlify dashboard
  # This is just for reference

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

